# Generated by Django 3.2.9 on 2022-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_numb', models.IntegerField()),
                ('price', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=255)),
                ('success_mess', models.CharField(max_length=255)),
                ('fail_mess', models.CharField(max_length=255)),
            ],
        ),
    ]
